### ISSUE TITLE
passes.hpp file extension

### ISSUE THREAD

**Issue by jeffsetter** [rdaly525/coreir#40]
All other header files in the include directory use .h while include/coreir-pass/passes.hpp uses a .hpp extension. I propose to switch this file to passes.h for consistency.

**Comment by THofstee** [comment]
Because there are a mix of c and c++ files in this repo now, maybe it would be better to name any C headers with .h and any C++ headers with .hpp?

**Comment by rdaly525** [comment]
I think in general that should be the case, but for anything in include/* we should name it as .h so that we can include them in the c api.

In the Readme, we have a well defined way of adding libraries so that we can use it in both the C api and the c++ api. 

Passes should probably do something similar.

**Comment by rdaly525** [comment]
This should be fixed by pull request #67
