### ISSUE TITLE
Fix bug in Instance.get_config_value

### ISSUE THREAD

**Issue by leonardt** [rdaly525/coreir#41]
@cdonovick Can you provide a simple example of where `get_config_value` returns a string for a constant?

**Comment by cdonovick** [comment]
It doesn't.


On May 1, 2017 3:16 PM, "Leonard Truong" <notifications@github.com> wrote:

@cdonovick <https://github.com/cdonovick> Can you provide a simple example
of where get_config_value returns a string for a constant?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rdaly525/coreir/issues/41>, or mute the thread
