### ISSUE TITLE
Change all the get functions which return strings to return a reference to the string

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#79]

**Comment by rdaly525** [comment]
Fixed from pull request #85

**Comment by THofstee** [comment]
Just ran into a bug with `COREDirectedConnectionGetSrc/Snk`, all the locations where there is a `newConstStringArray` points into a `std::vector<std::string>` from the C++ API, which is freed since nothing holds on to that vector. Either the char** needs to use malloc for each entry, or the vector needs to be added to a global list like some of the other functions.

**Comment by rdaly525** [comment]
@THofstee, Thanks I will try to fix this

**Comment by rdaly525** [comment]
@THofstee Can you confirm #92 fixes this issue?

**Comment by THofstee** [comment]
seems like it is fixed.
